In [16]:
import numpy as np
import pandas as pd
import random
from scipy.sparse import rand
from scipy.linalg import lu_factor, lu_solve, cho_factor, cho_solve
def A_matrix (U, L, density, m, n):
    #define a matrix of random values between 0 and 1 of specific density and size
    matrix=rand(m,n,density)
    #interpolate between upper and lower bounds with randomly generated number
    matrix = matrix*(U-L)+L
    #convert array to dataframe
    matrix_df=pd.DataFrame(matrix.toarray())
    #cycle through rows and check if all values in row are zero
    for row in matrix_df.index:
        if (matrix_df.loc[row,:]==0).all():
            print("restarting")
            #if all values in row are zero, restart function
            A_matrix(U,L,density,m,n)
    #cycle through columns and check if all values in column are zero
    for col in matrix_df.columns:
        if (matrix_df.loc[:,col]==0).all():
            #if all values in column are zero, restart function
            print("restarting")
            A_matrix(U,L,density,m,n)

    return matrix.toarray()

def b_matrix (U, L, density, m, n):
    #define a matrix of random values between 0 and 1 of specific density and size
    matrix=rand(m,n,density)
    #interpolate between upper and lower bounds with randomly generated number
    matrix = matrix*(U-L)+L
    #convert array to dataframe
    matrix_df=pd.DataFrame(matrix.toarray())
    #cycle through rows and check if all values in row are zero

    return matrix.toarray()

In [19]:
A=A_matrix(100,0,0.4,10,10)
b=b_matrix(50,0,0.8,10,1)
lu, piv = lu_factor(A)

x = lu_solve((lu, piv), b)
print(x)

[[ -1.37470446]
 [ -9.90285893]
 [  5.81719955]
 [  3.69713926]
 [-12.02755401]
 [  0.26239854]
 [  2.32051306]
 [  1.24323599]
 [ -2.24776885]
 [  1.0953921 ]]


In [20]:
x = np.linalg.solve(A,b)
print(x)

[[ -1.37470446]
 [ -9.90285893]
 [  5.81719955]
 [  3.69713926]
 [-12.02755401]
 [  0.26239854]
 [  2.32051306]
 [  1.24323599]
 [ -2.24776885]
 [  1.0953921 ]]


In [21]:
A_inv = np.linalg.inv(A)
print(A_inv.dot(b))


[[ -1.37470446]
 [ -9.90285893]
 [  5.81719955]
 [  3.69713926]
 [-12.02755401]
 [  0.26239854]
 [  2.32051306]
 [  1.24323599]
 [ -2.24776885]
 [  1.0953921 ]]


In [22]:
def is_pos_def(x):
    return np.all(np.linalg.eigvals(x) > 0)

def cho_fun (B):
    D=(1/2*(B+np.transpose(B)))
    if False == is_pos_def(D):
        np.fill_diagonal(D, D.diagonal() + 200)        
    return cho_solve(cho_factor(D),b)

cho_fun(A)


array([[-0.04062788],
       [-0.04562746],
       [ 0.13166917],
       [ 0.10101261],
       [ 0.21351472],
       [ 0.1877215 ],
       [ 0.03550723],
       [-0.11144251],
       [ 0.0435024 ],
       [-0.04814565]])

In [ ]:


def generate_dmat_old (B):
    D=(1/2*(B+np.transpose(B)))
    if False == is_pos_def(D):
        print("not pos def")
        return None
    return np.linalg.cholesky(D)